version: "3.8"

services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
      # Only build development stage from Dockerfile
      target: development
    # Mount our host dir to the docker container
    # Mount api directory (./api) to (:) docker container (/thomas/src/app)
    # Reflect File changes from host to container
    volumes:
      - ./api:/transaction/src/api
      - /transaction/src/api/node_modules/
    # RUN in debug mode: npm run start:debug --> Also start your vscode debugger
    # Run in dev mode: npm run start:dev
    command: npm run start:debug
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DB_USERNAME: patrick
      DB_PASSWORD: osofo
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: transaction_db
      DB_LOG_LEVEL: all
      DB_TYPE: postgres
      JWT_SECRET: PATRICKSECRET
    ports:
      - 3000:3000
      - 9229:9229

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
      target: development
    command: npm run start
    volumes:
      - ./client:/transaction/src/client
      - /transaction/src/client/node_modules
    ports:
      - 4200:4200
    links:
      - api

  db:
    image: postgres:12.4
    ports:
      - "54320:5432"
    expose:
      - "54320"
    restart: always
    environment:
      # if user, pass, and db changes, need to remove previous containers # docker-compose rm -vf
      - POSTGRES_USER=patrick
      - POSTGRES_PASSWORD=osofo
      - POSTGRES_DB=transaction_db
    volumes:
      - ./db_data:/var/lib/postgresql/data

volumes:
  db_data:


