version: "3.8"

services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
      target: development
    volumes:
      - ./api:/transaction/src/api
      - /transaction/src/api/node_modules/
    command: npm run start:debug
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://patrick:osofo@db:5432/transaction_db
      DB_LOG_LEVEL: all
      JWT_SECRET: PATRICKSECRET
      NODE_ENV: development
    ports:
      - 3000:3000

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
      target: development
    command: npm run start
    volumes:
      - ./client:/transaction/src/client
      - /transaction/src/client/node_modules
    ports:
      - 4200:4200
    links:
      - api

  db:
    image: postgres:12.4
    ports:
      - "54320:5432"
    expose:
      - "54320"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=patrick
      - POSTGRES_PASSWORD=osofo
      - POSTGRES_DB=transaction_db

volumes:
  db_data:


