version: "3.8"

services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
      # Only build development stage from Dockerfile
      target: development
    # Mount our host dir to the docker container
    # Mount api directory (./api) to (:) docker container (/thomas/src/app)
    # Reflect File changes from host to container
    volumes:
      - ./api:/transaction/src/api
      - /transaction/src/api/node_modules/
    # RUN in debug mode: npm run start:debug --> Also start your vscode debugger
    # Run in dev mode: npm run start:dev
    command: npm run start:debug
    depends_on:
      - postgres
    environment:
      DB_USERNAME: patrick
      DB_PASSWORD: osofo
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: transaction_db
      DB_LOG_LEVEL: all
      DB_TYPE: postgres
      JWT_SECRET: PATRICKSECRET
    ports:
      - 3000:3000
      - 9229:9229

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
      target: development
    command: npm run start
    volumes:
      - ./client:/transaction/src/client
      - /transaction/src/client/node_modules
    ports:
      - 4200:4200
    links:
      - api

  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_USER: patrick
      POSTGRES_PASSWORD: osofo
      POSTGRES_DB: transaction_db
    ports:
      - 35000:5432

  postgres_admin:
    image: dpage/pgadmin4:4.28
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80


